### ISSUE TITLE
Add Blog?

### ISSUE THREAD

**Issue by tyeeman** [dandalpiaz/markdown-pages#2]
This looks real interesting. Can a blog function be added easily? Actually, a blog is just pages with a front index of all the pages. You have all the pages here, just need to create the front index page of all the pages in that folder. What do you think?

**Comment by dandalpiaz** [comment]
Thanks for the interest!

Yes, I think a blog could be created by adding blog posts to the `pages` directory, e.g. `my-blog-post-1.md`, `my-blog-post-2.md`, etc. Then from the `README.md` file (which is treated as the homepage), create a list of links to those posts:

```
## Blog Posts

- [My Blog Post 1](?page=my-blog-post-1)
- [My Blog Post 2](?page=my-blog-post-2)
```

Which will render as:

## Blog Posts

- [My Blog Post 1](?page=my-blog-post-1)
- [My Blog Post 2](?page=my-blog-post-2)
